# Generated by Django 2.2.1 on 2019-05-08 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created',), 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('created',), 'verbose_name_plural': 'movies'},
        ),
    ]
