# Generated by Django 2.2.1 on 2019-05-12 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20190511_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'comments'},
        ),
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name_plural': 'movies'},
        ),
        migrations.AlterModelOptions(
            name='movierating',
            options={'verbose_name_plural': 'ratings'},
        ),
    ]
